# Generated by Django 4.2.6 on 2023-10-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='First day of trip')),
                ('end_date', models.DateField(verbose_name='Last day of trip')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('num_travelers', models.IntegerField(verbose_name='Number of travelers')),
            ],
        ),
    ]
