# Generated by Django 4.2.6 on 2023-10-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trektech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(verbose_name='First day of trip'),
        ),
    ]
